name: "run-tests"
description: "run-tests"

inputs:
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    required: true
    default: "."
  hstream-image:
    description: "hstream-image"
    required: true
    default: "hstreamdb/hstream:latest"
  distribution:
    description: "The distribution of java"
    required: true
    default: "adopt"
  java-version:
    description: "The version of java"
    required: true
    default: "11"
  tests_arg:
    description: "The argument of tests"
    required: true
  kafka_client_version:
    description: "The version of kafka client"
    required: true
  is_lagacy_tests:
    description: "Is lagacy tests"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
        cache: "gradle"

    - name: Run lagacy tests
      if: ${{ inputs.is_lagacy_tests == 'true' }}
      shell: bash
      run: |
        cd ${{ inputs.path }}
        echo "=> Run tests ${{ inputs.tests_arg }} with kafka client ${{ inputs.kafka_client_version }}"
        KAFKA_CLIENT_VERSION=${{ inputs.kafka_client_version }} \
        HSTREAM_IMAGE_NAME=${{ inputs.hstream-image }} \
          ./gradlew test -i --rerun-tasks ${{ inputs.tests_arg }}

    - name: Run tests
      if: ${{ inputs.is_lagacy_tests != 'true' }}
      shell: bash
      run: |
        cd ${{ inputs.path }}
        echo "=> Run tests ${{ matrix.tests.tests_arg }} with kafka client ${{ matrix.tests.kafka_client_version }}"
        KAFKA_CLIENT_VERSION=${{ matrix.tests.kafka_client_version }} \
        hstream_image=${{ inputs.hstream-image }} \
          ./script/run_test.sh -i --rerun-tasks ${{ matrix.tests.tests_arg }}

    - name: generate artifacts name (lagacy_tests)
      id: artifacts_lagacy
      if: ${{ inputs.is_lagacy_tests == 'true' && failure() }}
      shell: bash
      run: |
        name="reports-lagacy-kafka-tests-$(uuidgen)"
        echo "Reports name: $name"
        # NOTE: canot use GITHUB_ENV
        # https://github.com/orgs/community/discussions/51280
        echo "name=$name" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v4
      if: ${{ inputs.is_lagacy_tests == 'true' && failure() }}
      with:
        name: ${{ steps.artifacts_lagacy.outputs.name }}
        path: |
          ${{ inputs.path }}/.logs
          ${{ inputs.path }}/app/build/reports

    - name: generate artifacts name
      id: artifacts
      if: ${{ inputs.is_lagacy_tests != 'true' && failure() }}
      shell: bash
      run: |
        name="reports-kafka-tests-$(uuidgen)"
        echo "Reports name: $name"
        # NOTE: canot use GITHUB_ENV
        # https://github.com/orgs/community/discussions/51280
        echo "name=$name" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v4
      if: ${{ inputs.is_lagacy_tests != 'true' && failure() }}
      with:
        name: ${{ steps.artifacts.outputs.name }}
        path: |
          ${{ inputs.path }}/app/build/reports
